#!/usr/bin/csh
#
# ----- Mulvib execution script -----
#
#       Usage: mulvib name [ver]
#              name --> input/name.inp
#              ver      version to execute
#
# --- PCLINUX ---
#
set MVBRT=$HOME/projects/mulvib
set scr=/tmp/$USER/$1
mkdir /tmp/$USER
mkdir $scr
#
# set echo
if (null$2 == null) then
   set VERNO=00
else
   set VERNO=$2
endif
#
set MVB=$HOME/mulvib
set job=$1
#
date
echo ----- Mulvib execution script -----
#
#   Grab a copy of the input file
#
cp $MVB/input/$job.inp $scr/$job.f05
#
setenv input  $scr/$job.f05
setenv output $scr/$job.f06
setenv punch  $scr/$job.f07
setenv resta  $scr/$job.f08
#
#   ----- settings openMP -----
#
setenv OMP_WAIT_POLICY ACTIVE
setenv OMP_PROC_BIND SPREAD
setenv OMP_NUM_THREADS 6
setenv OMP_PLACES cores        # привязываем к физическим ядрам
#setenv OMP_NUM_THREADS 6
#setenv OMP_PLACES cores
#
#   ----- execute Mulvib -----
#
cp $MVBRT/mulvib_mpi.$VERNO.exe $scr
cp $MVBRT/hosts.txt $scr
cd $scr
mpirun --hostfile $scr/hosts.txt -np 2 --bind-to none $scr/mulvib_mpi.$VERNO.exe 
#
echo ------ accounting info ------
echo program version :  mulvib_mpi.$VERNO.exe
echo executed on :  `hostname`
echo executed at :  `date`
echo executed by :  $USER
echo -----------------------------
#
ls -lF $scr/$job.*
#
mkdir $MVB/output
cp $scr/$job.f06 $MVB/output/$job.out
if (-e $scr/$job.f07) cp $scr/$job.f07 $MVB/output/$job.dat
#
rm $scr/mulvib_mpi.$VERNO.exe
cd $HOME/mulvib
time
